apiVersion: v1
kind: Pod
metadata:
  name: with-affinity-preferred-weight
spec:
  affinity:
    nodeAffinity: # node affinity
# requiredDuringSchedulingIgnoredDuringExecution: # hard requirement
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions: # use matchExpressions for multiple conditions and these are labels on nodes. Multiple expressions under ine match extression is AND
          - key: kubernetes.io/os # Multilple match expressions are OR.
            operator: In. # operators: In, NotIn, Exists, DoesNotExist, Gt, Lt
            values:
            - linux
# preferredDuringSchedulingIgnoredDuringExecution: # soft requirement
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1 # weight can be between 1-100
        preference:
          matchExpressions: ## use matchExpressions for multiple conditions and these are labels on nodes
          - key: label-1
            operator: In
            values:
            - key-1
      - weight: 50
        preference:
          matchExpressions:
          - key: label-2
            operator: In
            values:
            - key-2
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:3.8
