apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-ebs-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-ebs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi # Must match the size of the PV or be less.