apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop-dev
data:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dev-deployment 
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: user
    environment: dev
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: user
      environment: dev  
      tier: backend
  template:
    metadata:
      name: user-dev-pod
      labels:
        project: roboshop
        app: user
        environment: dev
        tier: backend
    spec:
      containers:
      - name: user
        image: kar5113/user:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        ports:
        - name: test-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: test-port
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: user
    environment: dev
    tier: backend
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: user
    environment: dev
    tier: backend
  ports:  
    - protocol: TCP
      port: 8080
      targetPort: 8080
  