#### StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: roboshop-ebs
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---

#### Mongodb
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
spec:
  serviceName: mongodb-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mongodb
      environment: dev  
      tier: db
  template:
    metadata:
      name: mongodb
      labels:
        project: roboshop
        app: mongodb
        environment: dev
        tier: db
    spec:
      containers:
      - name: mongodb
        image: kar5113/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
      - metadata:
          name: mongodb
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: roboshop-ebs
          resources:
            requests:
              storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 27017
      targetPort: 27017



#### Mysql
# Similar to Mongodb, create StorageClass, Statefulset with PVC template, Headless service and ClusterIP service for Mysql database as per the requirements.

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
spec:
  serviceName: mysql-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mysql
      environment: dev  
      tier: db
  template:
    metadata:
      name: mysql
      labels:
        project: roboshop
        app: mysql
        environment: dev
        tier: db
    spec:
      
      containers:
      - name: mysql
        image: kar5113/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 80
          periodSeconds: 15
          failureThreshold: 2
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 80
          periodSeconds: 15
          failureThreshold: 2
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
      - metadata:
          name: mysql
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: roboshop-ebs
          resources:
            requests:
              storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 3306
      targetPort: 3306



#### Redis
# Similar to Mongodb, create StorageClass, Statefulset with PVC template, Headless service and ClusterIP service for Redis database as per the requirements.
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: redis
    environment: dev
    tier: db
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: redis
      environment: dev  
      tier: db
  template:
    metadata:
      name: redis
      labels:
        project: roboshop
        app: redis
        environment: dev
        tier: db
    spec:
      
      containers:
      - name: redis
        image: redis:7
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
      - metadata:
          name: redis
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: roboshop-ebs
          resources:
            requests:
              storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: redis
    environment: dev
    tier: db
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: redis
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: redis
    environment: dev
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: redis
    environment: dev    
    tier: db  
  ports:  
    - protocol: TCP
      port: 6379
      targetPort: 6379


#### Rabbitmq
# Similar to Mongodb, create StorageClass, Statefulset with PVC template, Headless service and ClusterIP service for Rabbitmq database as per the requirements.
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: rabbitmq
    environment: dev
    tier: db
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: rabbitmq
      environment: dev  
      tier: db
  template:
    metadata:
      name: rabbitmq
      labels:
        project: roboshop
        app: rabbitmq
        environment: dev
        tier: db
    spec:

      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "roboshop"
        - name: RABBITMQ_DEFAULT_PASS
          value: "roboshop123"
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
      - metadata:
          name: rabbitmq
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: roboshop-ebs
          resources:
            requests:
              storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: rabbitmq
    environment: dev
    tier: db
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: rabbitmq
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: rabbitmq
    environment: dev
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    app: rabbitmq
    environment: dev    
    tier: db  
  ports:  
    - protocol: TCP
      port: 5672
      targetPort: 5672  