apiVersion: v1
kind: ConfigMap
metadata: 
  name: frontend
  namespace: roboshop-dev
data: 
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /run/nginx.pid;

    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        keepalive_timeout   65;
        types_hash_max_size 4096;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        include /etc/nginx/conf.d/*.conf;
        # port i schanged to 8080 cause some clusters do not allow port 80 directly
        server {
            listen       8080;
            listen       [::]:8080;
            server_name  _;
            root         /usr/share/nginx/html;

            include /etc/nginx/default.d/*.conf;

            error_page 404 /404.html;
            location = /404.html {
            }

            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
            }

            location /images/ {
              expires 5s;
              root   /usr/share/nginx/html;
              try_files $uri /images/placeholder.jpg;
            }
            location /api/catalogue/ { proxy_pass http://catalogue:8080/; }
            location /api/user/ { proxy_pass http://user:8080/; }
            location /api/cart/ { proxy_pass http://cart:8080/; }
            location /api/shipping/ { proxy_pass http://shipping:8080/; }
            location /api/payment/ { proxy_pass http://payment:8080/; }
            location /health {
              stub_status on;
              access_log off;
            }

        }
    }


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: frontend
    environment: dev
    tier: frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      app: frontend
      environment: dev  
      tier: frontend
  template:
    metadata:
      name: frontend
      labels:
        project: roboshop
        app: frontend
        environment: dev
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: kar5113/frontend:{{ .Values.deployment.imageversion }}
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:  
            path: /
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        volumeMounts:
        - name: frontend-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: frontend-config
        configMap:
          name: frontend

     
--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: frontend
    environment: dev
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    app: frontend
    environment: dev
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
        