apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dev-deployment
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: redis
    environment: dev
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: redis
      environment: dev  
      tier: db
  template:
    metadata:
      name: redis-dev-pod
      labels:
        project: roboshop
        app: redis
        environment: dev
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379  
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: redis
    environment: dev
    tier: db
spec:
  selector:
    project: roboshop
    app: redis
    environment: dev
    tier: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379