
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-dev-deployment
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: rabbitmq
    environment: dev
    tier: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: rabbitmq
      environment: dev  
      tier: messaging
  template:
    metadata:
      name: rabbitmq
      labels:
        project: roboshop
        app: rabbitmq
        environment: dev
        tier: messaging
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672  
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop-dev
  labels:
    project: roboshop 
    app: rabbitmq
    environment: dev
    tier: messaging
spec:
  selector:
    project: roboshop
    app: rabbitmq
    environment: dev
    tier: messaging
  ports:
    - protocol: TCP 
      port: 5672
      targetPort: 5672