apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop-dev
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-dev-deployment 
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: shipping
    environment: dev
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: shipping
      environment: dev  
      tier: backend
  template:
    metadata:
      name: shipping-dev-pod
      labels:
        project: roboshop
        app: shipping
        environment: dev
        tier: backend
    spec:
      containers:
      - name: shipping
        image: kar5113/shipping:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: test-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: test-port
          initialDelaySeconds: 60
          failureThreshold: 3
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: shipping
    environment: dev
    tier: backend
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: shipping
    environment: dev
    tier: backend
  ports:  
    - protocol: TCP
      port: 8080
      targetPort: 8080
  