# a mock yaml for service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: roboshop-dev
  lables:
    app: my-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/MyEKSServiceAccountRole
secrets:
- name: my-service-account-token-abcde
imagePullSecrets:
- name: my-registry-secret
automountServiceAccountToken: true
---
# a mock yaml for role binding.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: roboshop-dev
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: roboshop-dev
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io
---
# a mock yaml for cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: roboshop-dev
roleRef:
  kind: ClusterRole
  name: my-cluster-role
  apiGroup: rbac.authorization.k8s.io
--- 
# yaml for the role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
  namespace: roboshop-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
# yaml for the cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"] 


___
# pod spec using the service account
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: roboshop-dev
spec:
  serviceAccountName: my-service-account
  containers:
  - name: my-container
    image: my-app-image:latest
    ports:
    - containerPort: 80 


## Instructions to create a service account with IAM role association
# 1. Ensure your EKS cluster has an OpenID Connect (OIDC) provider associated with it., if not do the following:
#    You can check this in the AWS Management Console under the EKS cluster details or by using the AWS CLI:
#    aws eks describe-cluster --name <cluster-name> --query "cluster.identity.oidc.issuer"  --output text
#    If there is no OIDC provider, you can create one using eksctl:
#    eksctl utils associate-iam-oidc-provider --cluster <cluster-name> --approve  or via AWS Console. 
#    In the AUsing AWS Console:
        # Go to the IAM console
        # Navigate to Identity providers
        # Click "Add provider"
        # Select "OpenID Connect"
        # For Provider URL, use your cluster's OIDC issuer URL (you can find this in your EKS cluster details)
        # For Audience, enter: sts.amazonaws.com
        # Click "Add provider"
# 2. Create an IAM role with a trust relationship that allows the EKS service account to assume the role. The trust relationship should look something like this:
#    {
#      "Version": "2012-10-17",
#      "Statement": [
#        {
#          "Effect": "Allow",
#          "Principal": {
#            "Federated": "arn:aws:iam::<AWS_ACCOUNT_ID>:oidc-provider/<OIDC_PROVIDER_URL>"
#          },
#          "Action": "sts:AssumeRoleWithWebIdentity",
#          "Condition": {
#            "StringEquals": {
#              "<OIDC_PROVIDER_URL>:sub": "system:serviceaccount:<namespace>:<service-account-name>"
#            }
#          }
#        }
#      ]
#    } [Just use eksctl to create the role with the service account, it automatically creates the trust relationship]
# 3. Attach the necessary IAM policies to the role to grant the required permissions.
# 4. Create the Kubernetes service account and annotate it with the IAM role ARN. You can use the provided YAML manifest above or use eksctl command:
#    eksctl create iamserviceaccount --name <service-account-name> --namespace <namespace> --cluster <cluster-name> --attach-policy-arn <policy-arn> --approve 
# 5. Deploy the service account manifest to your EKS cluster:
#    kubectl apply -f serviceaccount.yaml



# or you can create the service account directly using eksctl command as mentioned in step 4., when done with eksctl, give it the policy arn and it aytomatically creates the role .# eksctl create iamserviceaccount --name my-service-account --namespace roboshop-dev --cluster roboshop-d --attach-policy-arn arn:aws:iam::123456789012:policy/MyEKSServiceAccountPolicy --approve
