apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dev-deployment
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mongodb
      environment: dev  
      tier: db
  template:
    metadata:
      name: mongodb-dev-pod
      labels:
        project: roboshop
        app: mongodb
        environment: dev
        tier: db
    spec:
      containers:
      - name: mongodb
        image: kar5113/mongodb:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: mongodb
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 27017
      targetPort: 27017
  