apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity=2G

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dev-deployment
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: mysql
      environment: dev  
      tier: db
  template:
    metadata:
      name: mysql-dev-pod
      labels:
        project: roboshop
        app: mysql
        environment: dev
        tier: db
    spec:
      containers:
      - name: mysql
        image: kar5113/mysql:v1
        imagePullPolicy: Always
        env:
        envFrom:
        - configMapRef:
            name: mysql-config
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 100
          periodSeconds: 10


---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop-dev
  labels:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: mysql
    environment: dev
    tier: db
  ports:  
    - protocol: TCP
      port: 3306
      targetPort: 3306
  